### ISSUE TITLE
create functionality: car rental

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#10]
bot should know how to answer inputs such as

- where can i rent a car
- what do i need if i want to rent a car

the answer should contain a link to some car rental service
### nlu
create intent with at least 5-10 examples
### utter
create an answer for the intent
### rule
link the intent and the reaction utter
### domain
create a new domain file that will list nlu and utter

**Comment by alenalin** [comment]
#15 

will test

**Comment by alenalin** [comment]
testing done
