### ISSUE TITLE
create functionality: general tips for events and trips

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#11]
bot should know how to answer inputs such as

- where can i travel in czech republic
- what are some parties in prague
- interesting places to visit

the answer should contain a link to some events portal and top europe destinations

### nlu
create intent with at least 5-10 examples

### utter
create an answer for the intent

### rule
link the intent and the reaction utter

### domain
create a new domain file that will list nlu and utter (as seen for example in domain/healthcare.yml)

**Comment by alenalin** [comment]
new "trip_tips" intent created
tested, works
