### ISSUE TITLE
create functionality: whatsapp group

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#12]
bot should know how to answer inputs such as

- i want to join esn whatsapp group
- is there some whatsapp group with all the students
- do you have some chat group

the answer should contain a link to [https://linktr.ee/esncuprague](https://linktr.ee/esncuprague?fbclid=IwAR280sBFgMe1L2hqZK6C5FcoH3jDvdp0xo6ApoklT2GQLMxLlBGfUvKBxXA)

the answer should contain a link to some car rental service
### nlu
create intent with at least 5-10 examples
### rule
link the intent and the reaction utter
### domain
create a new domain file that will list nlu and utter (including the utter text)

**Comment by alenalin** [comment]
merged with #23
