### ISSUE TITLE
improve functionality: add ESNcard price

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#14]
modify the answer for `utter_buy_esn_card` so that the text includes its price: 300 CZK

### domain
update the utter in domain

**Comment by Abraham12611** [comment]
Hello 👋
I'm new to open source contributions and I think I can help.

**Comment by essare-rimaz** [comment]
Hey,
thanks for reaching out! I have modified the issue description so that its more explicit. Feel free to fix this. Thank you

**Comment by alenalin** [comment]
tested, works
