### ISSUE TITLE
create functionality: display events generation 1

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#22]
bot should know how to answer inputs such as

- are there some events happening today
- is there some party in prague
- where can i find list of events

### nlu
create intent with at least 5-10 examples

### utter
create an answer for the intent with a link to [linktree](https://www.facebook.com/ESNCUPrague/events)

### rule
link the intent and the reaction utter

### domain
create a new domain file that will list nlu and utter

**Comment by alenalin** [comment]
this one would partially overlap with trip_tips intent (however trip_tips does not include esn events, only general events in prague or czech republic)

**Comment by essare-rimaz** [comment]
duplicate #49

**Comment by essare-rimaz** [comment]
duplciate #49
