### ISSUE TITLE
create functionality: erasmus in schools

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#26]
bot should know how to answer inputs such as

- what is erasmus in schools
- i want to join EiS
- can i participate in erasmus in schools

### nlu
create intent with at least 5-10 examples

### utter
create an answer for the intent, it should contain link to the [registration form](https://tr.ee/TSFmb1-sn9)

### rule
link the intent and the reaction utter

###domain
create a new domain file that will list nlu and utter

**Comment by alenalin** [comment]
tested, works
