### ISSUE TITLE
improve functionality of office_hours

### ISSUE THREAD

**Issue by alenalin** [GerritChatbot/rasa_base#43]
office_hours needs to be improved to show the correct time & date

**Comment by essare-rimaz** [comment]
the office_hours custom action needs to be refactored
- right now it takes information from a mock excel
- ESN CU Prague is starting to implement an event management tool where office hours event will be created as well
- this tool can be access via [graphQL](https://cu-prague.esn.world/graphql)
- the new custom action should retrieve all events which are happening after current_datetime, filter out those which do not belong to Office Hours category and the retrieve the one which is closest in time (presumably the first one)

**Comment by essare-rimaz** [comment]
graphQL logic was added into actions via 571c99f0dc3cc9c2d443bdf5bd18b548428c2ba3
