### ISSUE TITLE
create functionality: buddy

### ISSUE THREAD

**Issue by essare-rimaz** [GerritChatbot/rasa_base#9]
bot should know how to answer inputs such as
- i want to have buddy
- how can i get a buddy
the answer should contain a link to the buddy system in broaddy
### nlu
- create intent with at least 5-10 examples
### utter
- create an answer for the intent 
### rule
- link the intent and the reaction utter
### domain
- create a new domain file that will list nlu and utter

**Comment by Foolishmay** [comment]
#16

**Comment by alenalin** [comment]
testing done
